spring:
 application:
   name: staybooking
 servlet:
   multipart:
     max-file-size: 10MB # File upload limit, default 1MB not enough.
 jackson:
   default-property-inclusion: non_null
 datasource:
   url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/postgres
   username: ${DATABASE_USERNAME:postgres}
   password:<REDACTED>
   driver-class-name: org.postgresql.Driver
 jpa:
   hibernate:
     ddl-auto: create-drop
   properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
       format_sql: true
 sql:
   init:
     mode: always
     schema-locations: "classpath:postgis_extension.sql"


logging:
 level:
   org.hibernate.SQL: DEBUG
   org.hibernate.orm.jdbc.bind: TRACE
