services:


 db:
   image: ghcr.io/baosystems/postgis:latest
   environment:
     POSTGRES_DB: postgres
     POSTGRES_PASSWORD: secret
     TZ: UTC
   volumes:
     - staybooking-pg-local:/var/lib/postgresql
   ports:
     - "5432:5432"


volumes:
 staybooking-pg-local:

docker compose up -d
